name: dropdown_search
description: Simple and reactive Searchable Dropdown with item search feature, making it possible to use an sync/async item for easy customization.
version: 6.0.3
homepage: https://github.com/salim-lachdhaf
git: https://github.com/salim-lachdhaf/dropdown_search
repository: https://github.com/salim-lachdhaf/dropdown_search

environment:
  sdk: ">=2.17.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.1

topics:
  - dropdown
  - autocomplete
  - form
  - material
  - popups
